language: ruby
services:
  - redis-server
rvm:
- 2.6.3
install:
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn
cache: bundler
before_script:
  - bundle exec rake db:create db:migrate RAILS_ENV=test
script:
  - bundle exec rails webpacker:compile
  - bundle exec rake
